# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 20:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20160110_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='capture_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 11, 20, 13, 2, 91326, tzinfo=utc)),
        ),
    ]
