# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 20:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20160111_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='site',
            field=models.URLField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='capture_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 11, 20, 26, 12, 47997, tzinfo=utc)),
        ),
    ]
